# ==========================================================
# 训练配置（对齐 ComfyUI 节点 ddcolor_rgb.yaml）
# - num_queries: 100
# - input_size: [256, 256]
# - output_mode: rgb
# 额外：通过 datasets.train/val.swap_ab 交换 A/B，以对齐节点推理的输入语义。
# ==========================================================

name: detail_refine_ddcolormask_node
model_type: DetailRefineModel
scale: 1
num_gpu: 1
manual_seed: 0

# ----------------- dataset and data loader settings -----------------
datasets:
  train:
    name: TrainSet
    type: TripletRefineDataset
    phase: train
    # meta: 每行三列：B_path A_path GT_path
    meta_info_file: data_list/ljt_detail_refine_train.txt
    io_backend:
      type: disk

    # 对齐节点：节点侧语义是 (detail, color) -> (content, style)
    # 而当前 meta 的列是 (B, A, GT)，因此训练侧需要交换 A/B。
    swap_ab: true

    # 关闭随机裁剪：gt_size 设为 ~（None）即可全图训练（仍会保留 flip/rot 增强）。
    gt_size: ~
    use_hflip: true
    use_rot: true

    # dataloader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: TripletRefineDataset
    phase: val
    meta_info_file: data_list/ljt_detail_refine_val.txt
    io_backend:
      type: disk

    swap_ab: true

# ----------------- network structures -----------------
network_g:
  type: DetailRefineDDColorMask
  # 注意：这里的参数名需要与训练侧 arch 的 __init__ 对齐（DetailRefineDDColorMask）。
  # ComfyUI 的 ddcolor_rgb.yaml 里有 decoder_name/num_input_channels/output_mode 等字段，
  # 训练侧实现不接受这些字段，直接照抄会报 unexpected keyword。
  encoder_name: convnext-l
  num_queries: 256
  num_scales: 3
  dec_layers: 9
  nf: 512
  out_channels: 3
  last_norm: Spectral
  encoder_from_pretrain: false
  input_size: [256, 256]
  do_imagenet_normalize: true

# ----------------- path -----------------
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# ----------------- training settings -----------------
train:
  ema_decay: 0
  optim_g:
    type: Adam
    lr: !!float 1e-4
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [25000, 50000, 75000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# ----------------- validation settings -----------------
val:
  val_freq: 1000
  save_img: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# ----------------- logging settings -----------------
logger:
  print_freq: 100
  save_snapshot_freq: ~
  save_checkpoint_freq: 1000
  use_tb_logger: true

# ----------------- dist training settings -----------------
dist_params:
  backend: nccl
  port: 29500
