# 方案3：双编码器（B控结构）+ A 高频纹理记忆 + 受控注入（效果上限优先）
# 用法：python basicsr/train.py -opt options/train/ljt_train_detail_refine_dualenc.yml

name: detail_refine_dualenc
model_type: DetailRefineModel
scale: 1
num_gpu: auto
manual_seed: 0

datasets:
  train:
    name: TripletTrain
    type: TripletRefineDataset
    meta_info_file: ["data_list/ljt_detail_refine_train.txt"]
    gt_size: 512
    use_hflip: True
    use_rot: False

    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 2
    pin_memory: True
    persistent_workers: True
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: TripletVal
    type: TripletRefineDataset
    meta_info_file: "data_list/ljt_detail_refine_val.txt"
    gt_size: ~

network_g:
  type: DetailRefineDualEnc
  encoder_name_b: convnext-l
  encoder_name_a: convnext-l
  num_queries: 256
  num_scales: 3
  dec_layers: 9
  nf: 512
  out_channels: 3
  last_norm: Spectral
  encoder_from_pretrain: True
  input_size: [512, 512]
  do_imagenet_normalize: True
  highpass_kernel: 5

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

train:
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0.01
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [25000, 40000]
    gamma: 0.5

  total_iter: 50000
  warmup_iter: -1

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1.0
      'conv4_4': 1.0
      'conv5_4': 1.0
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0

val:
  val_freq: 5000
  save_img: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

logger:
  print_freq: 100
  save_snapshot_freq: ~
  save_checkpoint_freq: 5000
  use_tb_logger: true

dist_params:
  backend: nccl
  port: 29500
